SET(CMAKE_SYSTEM_NAME Linux)

SET(CMAKE_C_COMPILER   x86_64-pc-linux-gnu-gcc)
SET(CMAKE_CXX_COMPILER x86_64-pc-linux-gnu-g++)

SET(CMAKE_FIND_ROOT_PATH /usr/x86_64-pc-linux-gnu)

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY BOTH)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLDUE BOTH)
